### ISSUE TITLE
DateTime 수정

### ISSUE THREAD

**Issue by StarJ0405** [StarJ0405/ShoppingMall#186]
LocalTiemDate에서 .getActiveDate().atZone(ZoneId.systemDefault()).toInstant().toEpochMilli();을 써서 변형합시다;;
yyyy-hh-mm-ss 와 같은 표기법은 Display에서만 사용하는 방식입니다;;
프로그래머는 1970년 1월 1일 기준 유닉스로 부터 시작한 밀리세컨드 방식으로 시간을 주고받아요 많이 당혹스럽네요;
해당 기준으로 사용하는 이유는 많은 컴퓨터의 시간 클래스 해당 시간 기준 밀리세컨드 후로 계산하고 있어서 시간 관련 클래스 사용에 용이하고요. 위 메소드에서 atZone을 사용하는 이유는 해당 지역을 한국으로 정확히는 시스템 설정된 지역으로 변경하여 밀리세컨드로 바꾸는 함수입니다. 알아두시면 좋습니다.

**Comment by 2ndsprout** [comment]
전공자가 아니라 몰랐네
2024-06-14 14:02:04.386 변형하면 1718329324386 이렇게 나오는데 이거 그대로 response 에 담아서 보내라는거지?

**Comment by StarJ0405** [comment]
> 전공자가 아니라 몰랐네
> 2024-06-14 14:02:04.386 변형하면 1718329324386 이렇게 나오는데 이거 그대로 response 에 담아서 보내라는거지?
> 

Yes 그게 1970년 1월1일 기준으로 그값더하면 현재시간이 나와
